{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyPygShbXjCN6j1cNugk/E6T"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":null,"metadata":{"id":"mlFzXqqZCdA6"},"outputs":[],"source":[]},{"cell_type":"markdown","source":["# **Exception Handling in Python**\n","\n","---\n","\n","\n","\n","Python provides a mechanism for handling exceptions using try, except, else, and finally blocks. This helps prevent the program from crashing when an error occurs and allows the programmer to deal with the error gracefully.\n"],"metadata":{"id":"UPkqo2z7CeF2"}},{"cell_type":"code","source":["try:\n","        result = 10 / 0\n","except ZeroDivisionError as e:\n","    print(f\"Error: {e}\")\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"Fh86GpuWChlC","executionInfo":{"status":"ok","timestamp":1741861584190,"user_tz":-330,"elapsed":15,"user":{"displayName":"Hitesh C","userId":"16426307530429038485"}},"outputId":"74a32c01-5fb4-4241-a73a-37c4b9abec41"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Error: division by zero\n"]}]},{"cell_type":"code","source":["result = 10 / 0"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":141},"id":"omKhRhcOCpQE","executionInfo":{"status":"error","timestamp":1741861597341,"user_tz":-330,"elapsed":69,"user":{"displayName":"Hitesh C","userId":"16426307530429038485"}},"outputId":"bff0bba9-64c0-45a8-f5d5-cbf761bd0c29"},"execution_count":2,"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-edcfe5e80815>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m10\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}]},{"cell_type":"code","source":["print(\"L1\")\n","try:\n","        result = 10 / 0\n","except ZeroDivisionError as e:\n","    print(\"Zero is not allowed in denominator, please give other numbe except zero\")\n","print(\"L2\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"GX5jNz1jCuFk","executionInfo":{"status":"ok","timestamp":1741862186842,"user_tz":-330,"elapsed":12,"user":{"displayName":"Hitesh C","userId":"16426307530429038485"}},"outputId":"227eaa63-09e6-4e9b-e31f-97277d345c8b"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["L1\n","Zero is not allowed in denominator, please give other numbe except zero\n","L2\n"]}]},{"cell_type":"code","source":["def func3():\n","    return 1 / 0  # ZeroDivisionError occurs here\n","\n","def func2():\n","    func3()  # Calls func3 (does not handle the error)\n","\n","def func1():\n","  try:\n","    func2()\n","  except:\n","    print(\"divide by zero\")\n","\n","func1()  # Calls func1 (no try-except anywhere)\n","print(\"hello\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"X2DZay4dDoLB","executionInfo":{"status":"ok","timestamp":1741862058563,"user_tz":-330,"elapsed":9,"user":{"displayName":"Hitesh C","userId":"16426307530429038485"}},"outputId":"32d3387e-0563-4fd0-af8f-2f7bb6ea97f5"},"execution_count":6,"outputs":[{"output_type":"stream","name":"stdout","text":["divide by zero\n","hello\n"]}]},{"cell_type":"markdown","source":["# **Example of catching an exception:**"],"metadata":{"id":"_MZciu95FCLA"}},{"cell_type":"code","source":["try:\n","    num = int(input(\"Enter a number: \"))\n","    print(f\"The square of the number is {num ** 2}\")\n","\n","except ValueError:\n","    print(\"That's not a valid number!\")\n","except ZeroDivisionError:\n","  print(\"divide by zero\")\n","except Exception as e:\n","  print(f\"{e}\")\n","\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"THc9NeYxFEcB","executionInfo":{"status":"ok","timestamp":1741862857091,"user_tz":-330,"elapsed":1761,"user":{"displayName":"Hitesh C","userId":"16426307530429038485"}},"outputId":"f15e910a-b80c-4ae8-da03-d87f9ee481e5"},"execution_count":16,"outputs":[{"output_type":"stream","name":"stdout","text":["Enter a number: abc\n","invalid literal for int() with base 10: 'abc'\n"]}]},{"cell_type":"markdown","source":["# **Using Multiple Except Blocks**\n","\n","---\n","\n","\n","You can handle different types of exceptions in different blocks:\n"],"metadata":{"id":"itEqJH-SH_b0"}},{"cell_type":"code","source":["try:\n","    number = int(input(\"Enter a number: \"))\n","    result = 10 / number\n","except ValueError:\n","    print(\"Error: Invalid input, please enter a valid number!\")\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero!\")\n","except Exception as e:\n","  print(f\"{e}\")\n","\n","print(\"I will always run\")\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"4OxquFL1ICXh","executionInfo":{"status":"ok","timestamp":1741863036333,"user_tz":-330,"elapsed":3023,"user":{"displayName":"Hitesh C","userId":"16426307530429038485"}},"outputId":"1e708dfd-7b76-4a45-863a-50f78ca798be"},"execution_count":19,"outputs":[{"output_type":"stream","name":"stdout","text":["Enter a number: 0\n","Error: You can't divide by zero!\n"]}]},{"cell_type":"markdown","source":["# **Finally Block**\n","\n","---\n","\n","\n","The finally block is always executed, regardless of whether an exception occurs or not. It's typically used for cleaning up resources, such as closing files or releasing connections.\n"],"metadata":{"id":"NyBb1IeRIetr"}},{"cell_type":"code","source":["import os\n","try:\n","    print(\"hello\")\n","    # file = open(\"file.txt\", \"r\")\n","    # content = file.read()\n","    os._exit(0)\n","except FileNotFoundError:\n","    print(\"File not found!\")\n","finally:\n","    print(\"Final Code\")  # Ensures that the file is closed even if an exception occurs\n"],"metadata":{"id":"Z6xynGvWIjYa"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["# **Custom Exceptions**\n","\n","---\n","\n","\n","You can also create your own exceptions by defining a new class that inherits from the built-in Exception class. This allows you to raise and handle your own specific errors.\n"],"metadata":{"id":"7WI2gpFCJ2F7"}},{"cell_type":"code","source":[],"metadata":{"id":"0FY3lnWCJvwA"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["def vote_eligibilty(age):\n","  if age<18:\n","    raise ArithmeticError(\"Age is less than 18 so not eligible for voting\")\n","  else:\n","    print(\"eligible for vote\")\n"],"metadata":{"id":"PNnEuz9VJ5uD","executionInfo":{"status":"ok","timestamp":1741863631348,"user_tz":-330,"elapsed":47,"user":{"displayName":"Hitesh C","userId":"16426307530429038485"}}},"execution_count":26,"outputs":[]},{"cell_type":"code","source":["try:\n","  vote_eligibilty(25)\n","except Exception as e:\n","  print(e)\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"0rLcQWfvKSrT","executionInfo":{"status":"ok","timestamp":1741863695305,"user_tz":-330,"elapsed":15,"user":{"displayName":"Hitesh C","userId":"16426307530429038485"}},"outputId":"18050d62-e070-4769-ed4e-e74bc342279e"},"execution_count":30,"outputs":[{"output_type":"stream","name":"stdout","text":["eligible for vote\n"]}]}]}